version: "3.0"

services:
  prometheus:
    image: haitranquangofficial/buda:prometheus
    restart: always
    ports:
      - 9090:9090
    extra_hosts:
      - "host.docker.internal:host-gateway"
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - 9999:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  prometheus-grafana:
